/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adrianrodriguezroqueiro;

import Controlador.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author a18adrianrr
 */
public class gestionProvincias extends javax.swing.JFrame {
private Controlador controlador;
    /**
     * Creates new form gestionProvincias
     */
    public gestionProvincias(Controlador controlador) {
        initComponents();
        this.controlador=controlador;
        actualizarComboProvincias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProvi = new javax.swing.JComboBox<>();
        jTextFieldProvincia = new javax.swing.JTextField();
        jButtonDeleteProvi = new javax.swing.JButton();
        jButtonaddProvi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Provincias");

        jLabel2.setText("Nueva");

        jComboBoxProvi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lugo", "Pontevedra", "Coruña", "Ourense" }));

        jButtonDeleteProvi.setText("Eliminar Provincia");
        jButtonDeleteProvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProviActionPerformed(evt);
            }
        });

        jButtonaddProvi.setText("Añadir Provincia");
        jButtonaddProvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddProviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxProvi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteProvi)
                    .addComponent(jButtonaddProvi))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxProvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDeleteProvi)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonaddProvi))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteProviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProviActionPerformed
       String provincia=(String)jComboBoxProvi.getSelectedItem();
       if(!provincia.isEmpty()){
          controlador.eliminarProvincia(provincia);
          actualizarComboProvincias();
       }else{
           JOptionPane.showMessageDialog(this, "selecciona una provincia para eliminar");
       }
    }//GEN-LAST:event_jButtonDeleteProviActionPerformed

    private void jButtonaddProviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddProviActionPerformed
        String provincia=(String)jTextFieldProvincia.getText().trim();
        if (!provincia.isEmpty()) {
            controlador.añadirProvincia(provincia);
            actualizarComboProvincias();
        }else{
            JOptionPane.showMessageDialog(this,"ingrese una provincia valida");
        }
        limpiarCampos();
    }//GEN-LAST:event_jButtonaddProviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   Controlador controlador=new Controlador(false);
                   new gestionProvincias(controlador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteProvi;
    private javax.swing.JButton jButtonaddProvi;
    private javax.swing.JComboBox<String> jComboBoxProvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldProvincia;
    // End of variables declaration//GEN-END:variables

    private void actualizarComboProvincias() {
       jComboBoxProvi.removeAllItems();
        for (String provincia : controlador.getProvincias()) {
            jComboBoxProvi.addItem(provincia);
        }
    }
    
    private void limpiarCampos(){
        jTextFieldProvincia.setText("");
    }
}
